
function logMap(){
  document.write('<div><h3><a href="https://0ekekddddd.github.io/">Landing</a></h3><h3><a href="https://0ekekddddd.github.io/log/update/">Update Log</a></h3><h3><a href="https://0ekekddddd.github.io/log/">Blog Directory</a></h3>'+ blogList +'<h3><a href="https://0ekekddddd.github.io/jfashion/">TKR Fashion</a></h3><h3><a href="https://0ekekddddd.github.io/luchino_shrine/">Church Of Luchino</a></h3><h3><a href="https://0ekekddddd.github.io/music/">私の音 My Music</a></h3></div>');
}
var blogList = '<table><tr><td><ul><li><a href="https://0ekekddddd.github.io/log/entry/bookmarks">Bookmarks</a></li><li><a href="https://0ekekddddd.github.io/log/entry/prospectoridvguide">Golden Guide To Playing Prospector (Identity V)</a></li><li><a href="https://0ekekddddd.github.io/log/entry/foolsgoldguide">Fool&apos;s Guide To Playing Fool&apos;s Gold (Identity V)</a></li><li><a href="https://0ekekddddd.github.io/log/entry/handinavibuildlog">Handinavi Build Log</a></li><li><a href="https://0ekekddddd.github.io/log/entry/htmlmosaics">HTML Mosaics</a></li><li><a href="https://0ekekddddd.github.io/log/entry/make-a-website">The SNS Model Is Failing: Why You Should Make A Website</a></li><li><a href="https://0ekekddddd.github.io/log/entry/openmptguide">OpenMPT Guide</a></li><li><a href="https://0ekekddddd.github.io/log/entry/splatoonbiology">Cephaling Biology</a> (Outdated)</li><li><a href="https://0ekekddddd.github.io/log/entry/miscsplatoontheories">Miscellaneous Splatoon Theories</a></li></ul></td></tr></table>';
function rssList(){
  document.write('<hr><center><a href="https://0ekekddddd.github.io/log/update/">update log</a> | <a href="https://0ekekddddd.github.io/log/">personal log</a> | <a href="https://0ekekddddd.github.io/rss/rss.xml">subscribe to the rss</a></center>');
}
function map(){
  document.write('<map name="top_h3nks"><area shape="rect" alt="[Home]" coords="389,19,631,89" href="https://0ekekddddd.github.io" target="_parent"></map><map name="bottom_h3nks"><area shape="rect" alt="[E-Mail Me]" title="[E-mail Me]" coords="43,61,74,88" href="mailto: 0ekekddddd@protonmail.com" target="_parent"><area alt="[Home]" title="[Home]" href="https://0ekekddddd.github.io" coords="131,49,182,95" shape="rect" target="_parent"><area alt="[Log]" title="[Log]" href="https://0ekekddddd.github.io/log/" coords="240,57,270,85" shape="rect" target="_parent"><area alt="[TOS/International]" title="[TOS/International]" href="https://gristlepod.github.io" coords="84,62,117,88" shape="rect"  target="_blank"><area alt="[My Music]" title="[My Music]" href="https://0ekekddddd.github.io/music/" coords="196,58,227,86" shape="rect" target="_parent"></map>');
}